# Generated by Django 3.2.4 on 2021-06-20 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pvs_suban', '0002_contact_salutation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('key', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='salutation',
            field=models.CharField(choices=[('herr', 'Herr'), ('frau', 'Frau'), ('familie', 'Familie'), ('andere', 'Andere')], default='frau', max_length=30),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=256)),
                ('zip', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=256)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Address', to='pvs_suban.contact')),
            ],
        ),
    ]
