# Generated by Django 3.2.4 on 2021-06-20 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pvs_suban', '0003_auto_20210620_1352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
    ]
