# Generated by Django 3.2.4 on 2021-06-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvs_suban', '0006_auto_20210620_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(default='Vor- und Nachname', max_length=256),
        ),
    ]
