# Generated by Django 3.2.4 on 2021-06-21 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pvs_suban', '0007_alter_contact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoiceposition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Invoice', to='pvs_suban.invoiceposition'),
        ),
    ]
