# Generated by Django 3.2.4 on 2021-06-21 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pvs_suban', '0009_auto_20210621_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countries', to='pvs_suban.country'),
        ),
        migrations.AlterField(
            model_name='country',
            name='value',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
