# Generated by Django 3.2.4 on 2021-06-21 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pvs_suban', '0010_auto_20210621_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses', to='pvs_suban.address'),
        ),
    ]
