# Generated by Django 3.2.4 on 2021-06-21 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pvs_suban', '0011_invoice_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoiceposition',
        ),
    ]
