# Generated by Django 3.2.4 on 2021-06-21 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pvs_suban', '0012_remove_invoice_invoiceposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceposition',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='InvoicePositions', to='pvs_suban.invoice'),
        ),
    ]
