# Generated by Django 3.2.4 on 2021-06-23 13:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvs_suban', '0013_alter_invoiceposition_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=256, validators=[django.core.validators.EmailValidator]),
        ),
    ]
